---
title: "intro"
author: "inryeol"
date: "2024-08-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

# R Notebook 예제

이 예제에서는 iris 데이터셋을 사용하여 데이터를 분석하고 시각화하는 과정을 보여줍니다.

```{r}
# 데이터셋 불러오기
data(iris)

# 데이터셋 구조 확인
str(iris)

# 데이터셋 요약
summary(iris)
```

# 데이터 시각화

## 히스토그램

```{r}
# 히스토그램: Sepal.Length 분포
hist(iris$Sepal.Length, main = "Histogram of Sepal Length", xlab = "Sepal Length", col = "lightblue", border = "black")
```

## 상자 그림 (Boxplot)

```{r}
# 상자 그림: Sepal.Length by Species
boxplot(Sepal.Length ~ Species, data = iris, main = "Boxplot of Sepal Length by Species", xlab = "Species", ylab = "Sepal Length", col = c("lightgreen", "lightblue", "lightpink"))
```

## 산점도 (Scatter Plot)

```{r}
# 산점도: Sepal.Length vs Petal.Length
plot(iris$Sepal.Length, iris$Petal.Length, main = "Scatter Plot of Sepal Length vs Petal Length", xlab = "Sepal Length", ylab = "Petal Length", col = iris$Species, pch = 19)
legend("topright", legend = levels(iris$Species), col = 1:3, pch = 19)
```

# 기초 통계 분석

## 평균 및 표준편차

```{r}
mean_sepal_length <- mean(iris$Sepal.Length)
sd_sepal_length <- sd(iris$Sepal.Length)

mean_petal_length <- mean(iris$Petal.Length)
sd_petal_length <- sd(iris$Petal.Length)

mean_sepal_length
sd_sepal_length
mean_petal_length
sd_petal_length
```

# 선형 회귀 분석

-   Sepal.Length를 종속 변수로, Petal.Length를 독립 변수로 하는 선형 회귀 모델

```{r}
# 선형 회귀 모델 생성
model <- lm(Sepal.Length ~ Petal.Length, data = iris)

# 회귀 모델 요약
summary(model)
```

## 회귀선 시각화

```{R}
# 회귀선 시각화
plot(iris$Sepal.Length ~ iris$Petal.Length, main = "Linear Regression: Sepal Length vs Petal Length", xlab = "Petal Length", ylab = "Sepal Length", col = iris$Species, pch = 19)
abline(model, col = "red", lwd = 2)
```
